name: 02 evento issue  
on: 
  push:
    paths-ignore:
      - '*.md'
  issues:
    types: [opened]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Aparece el nombre del step?
        run: echo "¡Probando Issue desde GITHUB ACTIONS!"